# directory where input is situated
input_dir: ./input
# output directory
output_dir: ./output
# busco db
busco_db: eukaryota_odb12
# amino acids (AA) or nucleotides (NT)
sequence_type: AA
# occupancy threshold for genes extraction
occupancy_threshold: 0.85
# tree template file location
tree_template: ./output_2/tree/tree.treefile
# settings for bootstrapping
bootstrapping:
  # execute?
  do: false
  # how many bootstraps do you want?
  sample_number: 100
  # how many genes in a bootstrap?
  sample_size: 10